config/routes.rb
Rails.application.routes.draw do
  resources :quarters
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quarter.rb
class Quarter < ApplicationRecord
  has_many :quarter_owners
  has_many :users, through: :quarter_owners
  validates :year, presence: true
  validates :degree_rust, presence: true
  validates :year, numericality: { greater_than: 1900 }
  validates :year, numericality: { greater_than: (Time.now.year - 5)}
  validates :degree_rust, numericality: { less_than: 70}
end

app/models/quarter_owner.rb
class QuarterOwner < ApplicationRecord
  belongs_to :user
  belongs_to :quarter
end

app/models/user.rb
class User < ApplicationRecord
  has_many :quarter_owners
  has_many :quarters, through: :quarter_owners
  validates :name, uniqueness: true
  validates :age, numericality: { greater_than: 17}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "application"
end

app/controllers/quarters_controller.rb
class QuartersController < ApplicationController
  def show
    @quarter = Quarter.find(params[:id])
  end

  def index
    @quarters = Quarter.all
  end

  def new
    @quarter = Quarter.new
  end

  def create
    @quarter = Quarter.new(quarter_params)
      if @quarter.valid?
        @quarter.save
        redirect_to @quarter
      else
        render :new
      end

  end


  def destroy
    @quarter = Quarter.find(params[:id]).destroy
    redirect_to quarters_path
  end



  private

  def quarter_params
    params.require(:quarter).permit(:degree_rust, :year)
  end







end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.valid?
        @user.save
        @user.quarters = quarter_id[:quarters].select{|id| id != ""}.map{|id| Quarter.find(id)}
        redirect_to @user
      else
        render :new
      end

  end

  def destroy
    @user = User.find(params[:id]).destroy
    redirect_to users_path
  end




private

def user_params
  params.require(:user).permit(:name, :age, :location)
end

def quarter_id
  params.require(:user).permit(quarters: [])
end






end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuarterToMany</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<style media="screen">
ul[target="navbar"]{
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: grey;
}

li[target="navlist"]{
  float: left;
}

li[target="navlist"]{
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

/* Change the link color to #111 (black) on hover */
li[target="navlist"] :hover {
  background-color: #111;
}
</style>


    <ul target="navbar">
      <li target="navlist"> <%= link_to "Quarters", quarters_path %> </li>
      <li target="navlist"> <%= link_to "Add Quarter", new_quarter_path %> </li>
      <li target="navlist"> <%= link_to "Users", users_path %> </li>
      <li target="navlist"> <%= link_to "Create User", new_user_path %> </li>
    </ul>
  <body>
    <%= yield %>
  </body>
</html>

app/views/quarters/index.html.erb
<h1>List of Quarters</h1><br>
  <ul>
      <% @quarters.each do |quarter| %>
      <li>ID: <%=link_to quarter.id, quarter %> Year: <%= quarter.year %> Degree Rust: <%= quarter.degree_rust %>
      <%= button_to "Delete Quarter", quarter_path(quarter), method: :delete, data: {confirm: "Do you really want to delete the Quarter?"}  %>
    </li>

      <% end %>

    </ul>

app/views/quarters/new.html.erb
<% if @quarter.errors.any?  %>
<% @quarter.errors.full_messages.each do |error| %>
  <%= error %><br>
  <% end %>
<% end %>
<h1>Create New Quarter</h1>

<%= form_for @quarter do |f|%>
  <%= f.label :year %>
  <%= f.text_field :year %> <br>

  <%= f.label :degree_rust %>
  <%= f.text_field :degree_rust %> <br>


  <%= f.submit "Create Quarter" %>
<% end %>

app/views/quarters/show.html.erb
<h1>Quarter ID: <%= @quarter.id %> Page </h1>
<%= button_to "Delete Quarter", quarter_path(@quarter), method: :delete, data: {confirm: "Do you really want to delete the Quarter?"}  %>

<h3>Quarters Previous Owner</h3>

<p>
  <ol>
    <% @quarter.users.reverse.each do |user| %>
    <li> Name: <%= link_to user.name, user %> || Age: <%= user.age %> || Location: <%= user.location %> </li>
    <% end %>
  </ol>
</p>

app/views/users/index.html.erb
<h1>List of Owners and their Quarters Previously or Currently Owned</h1><br>

<% @users.each do |user| %>
  <h3>Name: <%= link_to user.name, user %> || Age: <%= user.age %> || Location: <%= user.location %> </h3>
    <ul>
      <% user.quarters.each do |quarter| %>
      <li>ID: <%=link_to quarter.id, quarter %> Year: <%= quarter.year %> Degree Rust: <%= quarter.degree_rust %> </li>
      <% end %>
    </ul>
<% end %>

app/views/users/new.html.erb
<% if @user.errors.any?  %>
<% @user.errors.full_messages.each do |error| %>
  <%= error %>
  <% end %>
<% end %>

<h1>Create New User</h1>

<%= form_for @user do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %> <br>

  <%= f.label :age %>
  <%= f.text_field :age %> <br>

  <%= f.label :location %>
  <%= f.text_field :location %> <br>

  <%= f.label "Quarters Owned" %>
  <%= f.collection_check_boxes :quarters, Quarter.all, :id, :id %>


  <%= f.submit "Create User" %>
<% end %>

app/views/users/show.html.erb
<h1>  <%= @user.name %> </h1>
<%= button_to "Delete User", user_path(@user), method: :delete, data: {confirm: "Do you really want to delete the user?"}  %>
<h3>Previously Owner Quarters</h3>
  <ul>
    <% @user.quarters.each do |quarter| %>
        <li>ID: <%=link_to quarter.id, quarter %> Year: <%= quarter.year %> Degree Rust: <%= quarter.degree_rust %> </li>
    <% end %>
  </ul>